export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCES";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const LOGOUT = "LOGOUT";
export const LOGOUT_ERROR = "LOGOUT ERROR";
export const SET_ALERT = "set alert";
export const REMOVE_ALERT = "remove alert";
export const GET_ZONE = "GET_ZONE";
export const GET_SPACE_FAIL = "GET_SPACE_FAIL";
export const GET_SPACE = "GET_SPACE";
export const GET_VEHICLE_DETAIL = "GET_VEHICLE_DETAIL";
export const GET_VEHICLE_DETAIL_FAIL = "GET_VEHICLE_DETAIL_FAIL";
export const BOOK_VEHICLE = "BOOK_VEHICLE";
export const SORT_SPACE = "SORT_SPACE";
export const SORT_SPACE_FAIL = "SORT_SPACE_FAIL";
export const BOOK_VEHICLE_FAIL = "BOOK_VEHICLE_FAIL";
export const FILTER_SPACE = "FILTER_SPACE";
export const FILTER_SPACE_FAIL = "FILTER_SPACE_FAIL";
export const RELEASE_VEHICLE = "RELEASE_VEHICLE";
export const RELEASE_VEHICLE_FAIL = "RELEASE_VEHICLE_FAIL";
export const INIT_SPACE = "INIT SPACE"
export const INIT_SPACE_FAIL = "INIT SPACE_FAIL"
export const GET_REPORT = "GET_REPORT"
export const GET_REPORT_FAIL = "GET_REPORT_FAIL"